AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An Amazon API Gateway HTTP API and an AWS Lambda function.

Globals:
  Function:
    Runtime: nodejs20.x
    Handler: index.handler
    MemorySize: 128
    Timeout: 50
    Layers:
      - Ref: CommonLayer
    Environment:
      Variables:
        USER_TABLE: !Ref UserTable

Resources:
  MyApi: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/api-user
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        GetUserId:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/{user_id}
            Method: GET
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user
            Method: POST    

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST      

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-common-layer
      Description: Common utilities for Lambda functions
      ContentUri: layers/common
      CompatibleRuntimes:
        - nodejs20.x

  # S3Bucket:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     BucketName: !Ref S3BucketName
  #     CorsConfiguration:
  #       CorsRules:
  #         - AllowedOrigins:
  #             - '*'
  #           AllowedHeaders:
  #             - '*'
  #           AllowedMethods:
  #             - GET
  #           MaxAge: 3600
  #     VersioningConfiguration:
  #       Status: Enabled
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: aws:kms
  #             KMSMasterKeyID: !Ref CustomKMSArn      

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"